name: Lint Commit Messages

on: [ pull_request ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install modules
      - run: yarn install

      - name: Start commit lint
      - uses: wagoid/commitlint-github-action@v2
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules