name: Unit Test

on: [ pull_request ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn install

      - name: Build packages
        run: yarn lerna:build

      - name: Link dependencies
        run: yarn lerna:link

      - name: Run tests
        run: sudo yarn test

      - name: Analysis coverage
        run: yarn codecov
